import type { User, Message, FriendRequest, Chat } from './types';

export const currentUser: User = {
  id: 'user-0',
  name: 'Aarav Kumar',
  avatar: 'https://picsum.photos/seed/0/200/200',
  online: true,
};

export const users: User[] = [
  { id: 'user-1', name: 'Priya Patel', avatar: 'https://picsum.photos/seed/1/200/200', online: true },
  { id: 'user-2', name: 'Rohan Sharma', avatar: 'https://picsum.photos/seed/2/200/200', online: false },
  { id: 'user-3', name: 'Anjali Mehta', avatar: 'https://picsum.photos/seed/3/200/200', online: true },
  { id: 'user-4', name: 'Vikram Singh', avatar: 'https://picsum.photos/seed/4/200/200', online: false },
  { id: 'user-5', name: 'Sameer Khan', avatar: 'https://picsum.photos/seed/5/200/200', online: true },
  { id: 'user-6', name: 'Nisha Reddy', avatar: 'https://picsum.photos/seed/6/200/200', online: false },
  { id: 'user-7', name: 'Karan Desai', avatar: 'https://picsum.photos/seed/7/200/200', online: true },
  { id: 'user-8', name: 'Fatima Ali', avatar: 'https://picsum.photos/seed/8/200/200', online: true },
];

export const friends: User[] = [users[0], users[1], users[2]];

export const friendRequests: FriendRequest[] = [
  { id: 'req-1', user: users[4] },
  { id: 'req-2', user: users[5] },
];

// These suggestions would ideally be generated by the AI flow.
// For scaffolding purposes, we are using mock data.
export const friendSuggestions: User[] = [users[6], users[7]];

const messagesData: { [key: string]: Message[] } = {
  'user-1': [
    { id: 'msg-1-1', sender: users[0], content: 'Hey Priya! How are you?', timestamp: '10:00 AM' },
    { id: 'msg-1-2', sender: currentUser, content: 'Hi Aarav! I am good, thanks for asking. How about you?', timestamp: '10:01 AM' },
    { id: 'msg-1-3', sender: users[0], content: 'Doing great! Just working on a new project. It\'s exciting.', timestamp: '10:02 AM' },
    { id: 'msg-1-4', sender: currentUser, content: 'That sounds amazing! Tell me more about it.', timestamp: '10:03 AM' },
  ],
  'user-2': [
    { id: 'msg-2-1', sender: users[1], content: 'Hey, did you see the match last night?', timestamp: 'Yesterday' },
    { id: 'msg-2-2', sender: currentUser, content: 'Of course! It was a nail-biter.', timestamp: 'Yesterday' },
  ],
  'user-3': [
    { id: 'msg-3-1', sender: currentUser, content: 'Hi Anjali, are we still on for coffee tomorrow?', timestamp: '9:30 AM' },
    { id: 'msg-3-2', sender: users[2], content: 'Yes, absolutely! Looking forward to it.', timestamp: '9:31 AM' },
  ],
};

export const chats: Chat[] = friends.map(friend => ({
  friend,
  messages: messagesData[friend.id] || [],
}));
